[versions]
kotlin = "2.0.20"
ktor = "2.3.12"
neo4j = "5.21.0"
exposed = "0.50.1"
postgresql = "42.7.3"
hikari = "5.1.0"
koin = "3.5.6"
jwt = "4.4.0"
jbcrypt = "0.4"
lettuce = "6.3.2.RELEASE"
logback = "1.5.6"
typesafe-config = "1.4.3"
jackson = "2.17.0"
junit = "5.10.3"
neo4j-harness = "5.20.0"
slf4j = "2.0.13"
embedded-postgres = "2.0.4"
mockk = "1.13.11"
rest-assured = "5.4.0"

[libraries]
neo4j-driver = { module = "org.neo4j.driver:neo4j-java-driver", version.ref = "neo4j" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
neo4j-harness = { module = "org.neo4j.test:neo4j-harness", version.ref = "neo4j-harness" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
embedded-postgres = { module = "io.zonky.test:embedded-postgres", version.ref = "embedded-postgres" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
